version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: login_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Make PostgreSQL only accessible within the Docker network
    expose:
      - "5432"
    networks:
      - app-network

  backend:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/login_db
      - SECRET_KEY=your_secure_secret_key
      # Explicitly tell FastAPI where it's running
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
    restart: always
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://18.218.119.92:8000
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 